/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2026-04-29 14:48:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.bean.User;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1777445473812L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.bean.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
 
	User u=null;
	if(session!=null)
	{
		if(session.getAttribute("u")!=null)
		{
			u=(User)session.getAttribute("u");
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <!-- Required meta tags -->\r\n");
      out.write("  <meta charset=\"utf-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("  <link rel=\"icon\" href=\"img/favicon.png\" type=\"image/png\" />\r\n");
      out.write("  <title>Eiser ecommerce</title>\r\n");
      out.write("  <!-- Bootstrap CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/bootstrap.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/linericon/style.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/themify-icons.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/flaticon.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/owl-carousel/owl.carousel.min.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/lightbox/simpleLightbox.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/nice-select/css/nice-select.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/animate-css/animate.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/jquery-ui/jquery-ui.css\" />\r\n");
      out.write("  <!-- main css -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/responsive.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!--================Header Menu Area =================-->\r\n");
      out.write("  <header class=\"header_area\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"main_menu\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light w-100\">\r\n");
      out.write("          <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("          <a class=\"navbar-brand logo_h\" href=\"index.jsp\">\r\n");
      out.write("            <img src=\"img/logo.png\" alt=\"\" />\r\n");
      out.write("          </a>\r\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\r\n");
      out.write("            aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("          <div class=\"collapse navbar-collapse offset w-100\" id=\"navbarSupportedContent\">\r\n");
      out.write("            <div class=\"row w-100 mr-0\">\r\n");
      out.write("              <div class=\"col-lg-9 pr-0\">\r\n");
      out.write("                <ul class=\"nav navbar-nav center_nav pull-right\">\r\n");
      out.write("                  <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"index.jsp\">Home</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item submenu dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("                      aria-expanded=\"false\">Shop</a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"category.jsp\">Shop Category</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"single-product.jsp\">Product Details</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"checkout.jsp\">Product Checkout</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"cart.jsp\">Shopping Cart</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"contact.jsp\">Contact</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  ");

                  	if(u==null)
                  	{
                  
      out.write("\r\n");
      out.write("                 \r\n");
      out.write("                 <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"signup.jsp\">Sign Up</a>\r\n");
      out.write("                  </li> \r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"login.jsp\">Login</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  ");

                  	}
                  	else
                  	{
                  
      out.write("\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"change-password.jsp\">Change Password</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"logout.jsp\">Logout(");
      out.print(u.getFname() );
      out.write(")</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                   <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"profile.jsp\"><img src=\"profile_picture/");
      out.print(u.getProfile_picture());
      out.write("\" style=\"width: 50px;height: 50px;border-radius: 50%\"></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  ");

                  	}
                  
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"col-lg-3 pr-0\">\r\n");
      out.write("                <ul class=\"nav navbar-nav navbar-right right_nav pull-right\">\r\n");
      out.write("                  \r\n");
      out.write("\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"#\" class=\"icons\">\r\n");
      out.write("                      <i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"#\" class=\"icons\">\r\n");
      out.write("                      <i class=\"ti-heart\" aria-hidden=\"true\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("  <!--================Header Menu Area =================-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <!--================Home Banner Area =================-->\r\n");
      out.write("    <section class=\"banner_area\">\r\n");
      out.write("      <div class=\"banner_inner d-flex align-items-center\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div\r\n");
      out.write("            class=\"banner_content d-md-flex justify-content-between align-items-center\"\r\n");
      out.write("          >\r\n");
      out.write("            <div class=\"mb-3 mb-md-0\">\r\n");
      out.write("              <h2>Product Checkout</h2>\r\n");
      out.write("              <p>Very us move be blessed multiply night</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"page_link\">\r\n");
      out.write("              <a href=\"index.jsp\">Home</a>\r\n");
      out.write("              <a href=\"checkout.jsp\">Product Checkout</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--================End Home Banner Area =================-->\r\n");
      out.write("\r\n");
      out.write("    <!--================Checkout Area =================-->\r\n");
      out.write("    <section class=\"checkout_area section_gap\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"returning_customer\">\r\n");
      out.write("          <div class=\"check_title\">\r\n");
      out.write("            <h2>\r\n");
      out.write("              Returning Customer?\r\n");
      out.write("              <a href=\"#\">Click here to login</a>\r\n");
      out.write("            </h2>\r\n");
      out.write("          </div>\r\n");
      out.write("          <p>\r\n");
      out.write("            If you have shopped with us before, please enter your details in the\r\n");
      out.write("            boxes below. If you are a new customer, please proceed to the\r\n");
      out.write("            Billing & Shipping section.\r\n");
      out.write("          </p>\r\n");
      out.write("          <form\r\n");
      out.write("            class=\"row contact_form\"\r\n");
      out.write("            action=\"#\"\r\n");
      out.write("            method=\"post\"\r\n");
      out.write("            novalidate=\"novalidate\"\r\n");
      out.write("          >\r\n");
      out.write("            <div class=\"col-md-6 form-group p_star\">\r\n");
      out.write("              <input\r\n");
      out.write("                type=\"text\"\r\n");
      out.write("                class=\"form-control\"\r\n");
      out.write("                id=\"name\"\r\n");
      out.write("                name=\"name\"\r\n");
      out.write("                value=\" \"\r\n");
      out.write("              />\r\n");
      out.write("              <span\r\n");
      out.write("                class=\"placeholder\"\r\n");
      out.write("                data-placeholder=\"Username or Email\"\r\n");
      out.write("              ></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 form-group p_star\">\r\n");
      out.write("              <input\r\n");
      out.write("                type=\"password\"\r\n");
      out.write("                class=\"form-control\"\r\n");
      out.write("                id=\"password\"\r\n");
      out.write("                name=\"password\"\r\n");
      out.write("                value=\"\"\r\n");
      out.write("              />\r\n");
      out.write("              <span class=\"placeholder\" data-placeholder=\"Password\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-12 form-group\">\r\n");
      out.write("              <button type=\"submit\" value=\"submit\" class=\"btn submit_btn\">\r\n");
      out.write("                Send Message\r\n");
      out.write("              </button>\r\n");
      out.write("              <div class=\"creat_account\">\r\n");
      out.write("                <input type=\"checkbox\" id=\"f-option\" name=\"selector\" />\r\n");
      out.write("                <label for=\"f-option\">Remember me</label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <a class=\"lost_pass\" href=\"#\">Lost your password?</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cupon_area\">\r\n");
      out.write("          <div class=\"check_title\">\r\n");
      out.write("            <h2>\r\n");
      out.write("              Have a coupon?\r\n");
      out.write("              <a href=\"#\">Click here to enter your code</a>\r\n");
      out.write("            </h2>\r\n");
      out.write("          </div>\r\n");
      out.write("          <input type=\"text\" placeholder=\"Enter coupon code\" />\r\n");
      out.write("          <a class=\"tp_btn\" href=\"#\">Apply Coupon</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"billing_details\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-8\">\r\n");
      out.write("              <h3>Billing Details</h3>\r\n");
      out.write("              <form\r\n");
      out.write("                class=\"row contact_form\"\r\n");
      out.write("                action=\"#\"\r\n");
      out.write("                method=\"post\"\r\n");
      out.write("                novalidate=\"novalidate\"\r\n");
      out.write("              >\r\n");
      out.write("                <div class=\"col-md-6 form-group p_star\">\r\n");
      out.write("                  <input\r\n");
      out.write("                    type=\"text\"\r\n");
      out.write("                    class=\"form-control\"\r\n");
      out.write("                    id=\"first\"\r\n");
      out.write("                    name=\"name\"\r\n");
      out.write("                  />\r\n");
      out.write("                  <span\r\n");
      out.write("                    class=\"placeholder\"\r\n");
      out.write("                    data-placeholder=\"First name\"\r\n");
      out.write("                  ></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 form-group p_star\">\r\n");
      out.write("                  <input\r\n");
      out.write("                    type=\"text\"\r\n");
      out.write("                    class=\"form-control\"\r\n");
      out.write("                    id=\"last\"\r\n");
      out.write("                    name=\"name\"\r\n");
      out.write("                  />\r\n");
      out.write("                  <span class=\"placeholder\" data-placeholder=\"Last name\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12 form-group\">\r\n");
      out.write("                  <input\r\n");
      out.write("                    type=\"text\"\r\n");
      out.write("                    class=\"form-control\"\r\n");
      out.write("                    id=\"company\"\r\n");
      out.write("                    name=\"company\"\r\n");
      out.write("                    placeholder=\"Company name\"\r\n");
      out.write("                  />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 form-group p_star\">\r\n");
      out.write("                  <input\r\n");
      out.write("                    type=\"text\"\r\n");
      out.write("                    class=\"form-control\"\r\n");
      out.write("                    id=\"number\"\r\n");
      out.write("                    name=\"number\"\r\n");
      out.write("                  />\r\n");
      out.write("                  <span\r\n");
      out.write("                    class=\"placeholder\"\r\n");
      out.write("                    data-placeholder=\"Phone number\"\r\n");
      out.write("                  ></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 form-group p_star\">\r\n");
      out.write("                  <input\r\n");
      out.write("                    type=\"text\"\r\n");
      out.write("                    class=\"form-control\"\r\n");
      out.write("                    id=\"email\"\r\n");
      out.write("                    name=\"compemailany\"\r\n");
      out.write("                  />\r\n");
      out.write("                  <span\r\n");
      out.write("                    class=\"placeholder\"\r\n");
      out.write("                    data-placeholder=\"Email Address\"\r\n");
      out.write("                  ></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12 form-group p_star\">\r\n");
      out.write("                  <select class=\"country_select\">\r\n");
      out.write("                    <option value=\"1\">Country</option>\r\n");
      out.write("                    <option value=\"2\">Country</option>\r\n");
      out.write("                    <option value=\"4\">Country</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12 form-group p_star\">\r\n");
      out.write("                  <input\r\n");
      out.write("                    type=\"text\"\r\n");
      out.write("                    class=\"form-control\"\r\n");
      out.write("                    id=\"add1\"\r\n");
      out.write("                    name=\"add1\"\r\n");
      out.write("                  />\r\n");
      out.write("                  <span\r\n");
      out.write("                    class=\"placeholder\"\r\n");
      out.write("                    data-placeholder=\"Address line 01\"\r\n");
      out.write("                  ></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12 form-group p_star\">\r\n");
      out.write("                  <input\r\n");
      out.write("                    type=\"text\"\r\n");
      out.write("                    class=\"form-control\"\r\n");
      out.write("                    id=\"add2\"\r\n");
      out.write("                    name=\"add2\"\r\n");
      out.write("                  />\r\n");
      out.write("                  <span\r\n");
      out.write("                    class=\"placeholder\"\r\n");
      out.write("                    data-placeholder=\"Address line 02\"\r\n");
      out.write("                  ></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12 form-group p_star\">\r\n");
      out.write("                  <input\r\n");
      out.write("                    type=\"text\"\r\n");
      out.write("                    class=\"form-control\"\r\n");
      out.write("                    id=\"city\"\r\n");
      out.write("                    name=\"city\"\r\n");
      out.write("                  />\r\n");
      out.write("                  <span class=\"placeholder\" data-placeholder=\"Town/City\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12 form-group p_star\">\r\n");
      out.write("                  <select class=\"country_select\">\r\n");
      out.write("                    <option value=\"1\">District</option>\r\n");
      out.write("                    <option value=\"2\">District</option>\r\n");
      out.write("                    <option value=\"4\">District</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12 form-group\">\r\n");
      out.write("                  <input\r\n");
      out.write("                    type=\"text\"\r\n");
      out.write("                    class=\"form-control\"\r\n");
      out.write("                    id=\"zip\"\r\n");
      out.write("                    name=\"zip\"\r\n");
      out.write("                    placeholder=\"Postcode/ZIP\"\r\n");
      out.write("                  />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12 form-group\">\r\n");
      out.write("                  <div class=\"creat_account\">\r\n");
      out.write("                    <input type=\"checkbox\" id=\"f-option2\" name=\"selector\" />\r\n");
      out.write("                    <label for=\"f-option2\">Create an account?</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12 form-group\">\r\n");
      out.write("                  <div class=\"creat_account\">\r\n");
      out.write("                    <h3>Shipping Details</h3>\r\n");
      out.write("                    <input type=\"checkbox\" id=\"f-option3\" name=\"selector\" />\r\n");
      out.write("                    <label for=\"f-option3\">Ship to a different address?</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <textarea\r\n");
      out.write("                    class=\"form-control\"\r\n");
      out.write("                    name=\"message\"\r\n");
      out.write("                    id=\"message\"\r\n");
      out.write("                    rows=\"1\"\r\n");
      out.write("                    placeholder=\"Order Notes\"\r\n");
      out.write("                  ></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4\">\r\n");
      out.write("              <div class=\"order_box\">\r\n");
      out.write("                <h2>Your Order</h2>\r\n");
      out.write("                <ul class=\"list\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"#\"\r\n");
      out.write("                      >Product\r\n");
      out.write("                      <span>Total</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"#\"\r\n");
      out.write("                      >Fresh Blackberry\r\n");
      out.write("                      <span class=\"middle\">x 02</span>\r\n");
      out.write("                      <span class=\"last\">$720.00</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"#\"\r\n");
      out.write("                      >Fresh Tomatoes\r\n");
      out.write("                      <span class=\"middle\">x 02</span>\r\n");
      out.write("                      <span class=\"last\">$720.00</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"#\"\r\n");
      out.write("                      >Fresh Brocoli\r\n");
      out.write("                      <span class=\"middle\">x 02</span>\r\n");
      out.write("                      <span class=\"last\">$720.00</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <ul class=\"list list_2\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"#\"\r\n");
      out.write("                      >Subtotal\r\n");
      out.write("                      <span>$2160.00</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"#\"\r\n");
      out.write("                      >Shipping\r\n");
      out.write("                      <span>Flat rate: $50.00</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"#\"\r\n");
      out.write("                      >Total\r\n");
      out.write("                      <span>$2210.00</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"payment_item\">\r\n");
      out.write("                  <div class=\"radion_btn\">\r\n");
      out.write("                    <input type=\"radio\" id=\"f-option5\" name=\"selector\" />\r\n");
      out.write("                    <label for=\"f-option5\">Check payments</label>\r\n");
      out.write("                    <div class=\"check\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Please send a check to Store Name, Store Street, Store Town,\r\n");
      out.write("                    Store State / County, Store Postcode.\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"payment_item active\">\r\n");
      out.write("                  <div class=\"radion_btn\">\r\n");
      out.write("                    <input type=\"radio\" id=\"f-option6\" name=\"selector\" />\r\n");
      out.write("                    <label for=\"f-option6\">Paypal </label>\r\n");
      out.write("                    <img src=\"img/product/single-product/card.jpg\" alt=\"\" />\r\n");
      out.write("                    <div class=\"check\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Please send a check to Store Name, Store Street, Store Town,\r\n");
      out.write("                    Store State / County, Store Postcode.\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"creat_account\">\r\n");
      out.write("                  <input type=\"checkbox\" id=\"f-option4\" name=\"selector\" />\r\n");
      out.write("                  <label for=\"f-option4\">I’ve read and accept the </label>\r\n");
      out.write("                  <a href=\"#\">terms & conditions*</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a class=\"main_btn\" href=\"#\">Proceed to Paypal</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--================End Checkout Area =================-->\r\n");
      out.write("\r\n");
      out.write("    <!--================ start footer Area  =================-->\r\n");
      out.write("    <footer class=\"footer-area section_gap\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-2 col-md-6 single-footer-widget\">\r\n");
      out.write("            <h4>Top Products</h4>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">Managed Website</a></li>\r\n");
      out.write("              <li><a href=\"#\">Manage Reputation</a></li>\r\n");
      out.write("              <li><a href=\"#\">Power Tools</a></li>\r\n");
      out.write("              <li><a href=\"#\">Marketing Service</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-2 col-md-6 single-footer-widget\">\r\n");
      out.write("            <h4>Quick Links</h4>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">Jobs</a></li>\r\n");
      out.write("              <li><a href=\"#\">Brand Assets</a></li>\r\n");
      out.write("              <li><a href=\"#\">Investor Relations</a></li>\r\n");
      out.write("              <li><a href=\"#\">Terms of Service</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-2 col-md-6 single-footer-widget\">\r\n");
      out.write("            <h4>Features</h4>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">Jobs</a></li>\r\n");
      out.write("              <li><a href=\"#\">Brand Assets</a></li>\r\n");
      out.write("              <li><a href=\"#\">Investor Relations</a></li>\r\n");
      out.write("              <li><a href=\"#\">Terms of Service</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-2 col-md-6 single-footer-widget\">\r\n");
      out.write("            <h4>Resources</h4>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">Guides</a></li>\r\n");
      out.write("              <li><a href=\"#\">Research</a></li>\r\n");
      out.write("              <li><a href=\"#\">Experts</a></li>\r\n");
      out.write("              <li><a href=\"#\">Agencies</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-4 col-md-6 single-footer-widget\">\r\n");
      out.write("            <h4>Newsletter</h4>\r\n");
      out.write("            <p>You can trust us. we only send promo offers,</p>\r\n");
      out.write("            <div class=\"form-wrap\" id=\"mc_embed_signup\">\r\n");
      out.write("              <form target=\"_blank\" action=\"https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01\"\r\n");
      out.write("                method=\"get\" class=\"form-inline\">\r\n");
      out.write("                <input class=\"form-control\" name=\"EMAIL\" placeholder=\"Your Email Address\" onfocus=\"this.placeholder = ''\"\r\n");
      out.write("                  onblur=\"this.placeholder = 'Your Email Address '\" required=\"\" type=\"email\">\r\n");
      out.write("                <button class=\"click-btn btn btn-default\">Subscribe</button>\r\n");
      out.write("                <div style=\"position: absolute; left: -5000px;\">\r\n");
      out.write("                  <input name=\"b_36c4fd991d266f23781ded980_aefe40901a\" tabindex=\"-1\" value=\"\" type=\"text\">\r\n");
      out.write("                </div>\r\n");
      out.write("  \r\n");
      out.write("                <div class=\"info\"></div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-bottom row align-items-center\">\r\n");
      out.write("          <p class=\"footer-text m-0 col-lg-8 col-md-12\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("          <div class=\"col-lg-4 col-md-12 footer-social\">\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-dribbble\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-behance\"></i></a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!--================ End footer Area  =================-->\r\n");
      out.write("\r\n");
      out.write("    <!-- Optional JavaScript -->\r\n");
      out.write("    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("    <script src=\"js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"js/popper.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/stellar.js\"></script>\r\n");
      out.write("    <script src=\"vendors/lightbox/simpleLightbox.min.js\"></script>\r\n");
      out.write("    <script src=\"vendors/nice-select/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"vendors/isotope/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"vendors/isotope/isotope-min.js\"></script>\r\n");
      out.write("    <script src=\"vendors/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("    <script src=\"js/mail-script.js\"></script>\r\n");
      out.write("    <script src=\"vendors/jquery-ui/jquery-ui.js\"></script>\r\n");
      out.write("    <script src=\"vendors/counter-up/jquery.waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"vendors/counter-up/jquery.counterup.js\"></script>\r\n");
      out.write("    <script src=\"js/theme.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
