/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2026-05-04 11:56:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.dao.ProductDao;
import com.bean.Product;
import com.dao.CartDao;
import com.bean.Cart;
import java.util.List;
import com.bean.User;

public final class orders_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1777875519967L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dao.CartDao");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.dao.ProductDao");
    _jspx_imports_classes.add("com.bean.User");
    _jspx_imports_classes.add("com.bean.Cart");
    _jspx_imports_classes.add("com.bean.Product");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
 
	User u=null;
	if(session!=null)
	{
		if(session.getAttribute("u")!=null)
		{
			u=(User)session.getAttribute("u");
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <!-- Required meta tags -->\r\n");
      out.write("  <meta charset=\"utf-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("  <link rel=\"icon\" href=\"img/favicon.png\" type=\"image/png\" />\r\n");
      out.write("  <title>Eiser ecommerce</title>\r\n");
      out.write("  <!-- Bootstrap CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/bootstrap.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/linericon/style.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/themify-icons.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/flaticon.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/owl-carousel/owl.carousel.min.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/lightbox/simpleLightbox.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/nice-select/css/nice-select.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/animate-css/animate.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/jquery-ui/jquery-ui.css\" />\r\n");
      out.write("  <!-- main css -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/responsive.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!--================Header Menu Area =================-->\r\n");
      out.write("  <header class=\"header_area\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"main_menu\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light w-100\">\r\n");
      out.write("          <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("          <a class=\"navbar-brand logo_h\" href=\"index.jsp\">\r\n");
      out.write("            <img src=\"img/logo.png\" alt=\"\" />\r\n");
      out.write("          </a>\r\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\r\n");
      out.write("            aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("          <div class=\"collapse navbar-collapse offset w-100\" id=\"navbarSupportedContent\">\r\n");
      out.write("            <div class=\"row w-100 mr-0\">\r\n");
      out.write("              <div class=\"col-lg-9 pr-0\">\r\n");
      out.write("                <ul class=\"nav navbar-nav center_nav pull-right\">\r\n");
      out.write("                  <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"index.jsp\">Home</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item submenu dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("                      aria-expanded=\"false\">Shop</a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"category.jsp\">Shop Category</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"single-product.jsp\">Product Details</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"checkout.jsp\">Product Checkout</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"cart.jsp\">Shopping Cart</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"contact.jsp\">Contact</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  ");

                  	if(u==null)
                  	{
                  
      out.write("\r\n");
      out.write("                 \r\n");
      out.write("                 <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"signup.jsp\">Sign Up</a>\r\n");
      out.write("                  </li> \r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"login.jsp\">Login</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  ");

                  	}
                  	else
                  	{
                  
      out.write("\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"change-password.jsp\">Change Password</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"orders.jsp\">My Orders</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"logout.jsp\">Logout</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                   <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"profile.jsp\"><img src=\"profile_picture/");
      out.print(u.getProfile_picture());
      out.write("\" style=\"width: 50px;height: 50px;border-radius: 50%\"></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  ");

                  	}
                  
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"col-lg-3 pr-0\">\r\n");
      out.write("                <ul class=\"nav navbar-nav navbar-right right_nav pull-right\">\r\n");
      out.write("                  \r\n");
      out.write("                  ");

                  	if(u!=null)
                  	{
                  
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"cart.jsp\" class=\"icons\">\r\n");
      out.write("                      <i class=\"ti-shopping-cart\">");
      out.print(session.getAttribute("cart_count") );
      out.write("</i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"wishlist.jsp\" class=\"icons\">\r\n");
      out.write("                      <i class=\"ti-heart\" aria-hidden=\"true\">");
      out.print(session.getAttribute("wishlist_count") );
      out.write("</i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  ");

                  	}
                  
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("  <!--================Header Menu Area =================-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("    \r\n");
      out.write("    <!--================Header Menu Area =================-->\r\n");
      out.write("\r\n");
      out.write("    <!--================Home Banner Area =================-->\r\n");
      out.write("    <section class=\"banner_area\">\r\n");
      out.write("      <div class=\"banner_inner d-flex align-items-center\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div\r\n");
      out.write("            class=\"banner_content d-md-flex justify-content-between align-items-center\"\r\n");
      out.write("          >\r\n");
      out.write("            <div class=\"mb-3 mb-md-0\">\r\n");
      out.write("              <h2>Cart</h2>\r\n");
      out.write("              <p>Very us move be blessed multiply night</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"page_link\">\r\n");
      out.write("              <a href=\"index.jsp\">Home</a>\r\n");
      out.write("              <a href=\"cart.jsp\">Cart</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--================End Home Banner Area =================-->\r\n");
      out.write("\r\n");
      out.write("    <!--================Cart Area =================-->\r\n");
      out.write("    <section class=\"cart_area\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"cart_inner\">\r\n");
      out.write("          <div class=\"table-responsive\">\r\n");
      out.write("            <table class=\"table\">\r\n");
      out.write("              <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"col\">Product</th>\r\n");
      out.write("                  <th scope=\"col\">Price</th>\r\n");
      out.write("                  <th scope=\"col\">Quantity</th>\r\n");
      out.write("                  <th scope=\"col\">Total</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </thead>\r\n");
      out.write("              <tbody>\r\n");
      out.write("              	");

              		
              		List<Cart> list=CartDao.getOrders(u.getUid());
              		for(Cart c:list)
              		{
              			
              			Product p=ProductDao.getProduct(c.getPid());
              	
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td>\r\n");
      out.write("                    <div class=\"media\">\r\n");
      out.write("                      <div class=\"d-flex\">\r\n");
      out.write("                        <img\r\n");
      out.write("                          src=\"product_picture/");
      out.print(p.getProduct_image() );
      out.write("\" style=\"width: 100px;height: 100px;border-radius: 50%\";\r\n");
      out.write("                          alt=\"\"\r\n");
      out.write("                        />\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"media-body\">\r\n");
      out.write("                        <p>");
      out.print(p.getProduct_name() );
      out.write("</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </td>\r\n");
      out.write("                  <td>\r\n");
      out.write("                    <h5>");
      out.print(p.getProduct_price() );
      out.write("</h5>\r\n");
      out.write("                  </td>\r\n");
      out.write("                  <td>\r\n");
      out.write("                    <div class=\"product_count\">\r\n");
      out.write("                      \r\n");
      out.write("                      <form name=\"change-qty\" method=\"post\" action=\"change-qty.jsp\">\r\n");
      out.write("                      	<input type=\"hidden\" name=\"cid\" value=\"");
      out.print(c.getCid());
      out.write("\">\r\n");
      out.write("                      	<input type=\"number\" min=\"1\" max=\"10\" name=\"product_qty\" value=\"");
      out.print(c.getProduct_qty());
      out.write("\" readonly=\"readonly\"\">\r\n");
      out.write("                      </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </td>\r\n");
      out.write("                  <td>\r\n");
      out.write("                    <h5>");
      out.print(c.getTotal_price());
      out.write("</h5>\r\n");
      out.write("                  </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");

              		}
                
      out.write("\r\n");
      out.write("              </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--================End Cart Area =================-->\r\n");
      out.write("\r\n");
      out.write("    <!--================ start footer Area  =================-->\r\n");
      out.write("    <footer class=\"footer-area section_gap\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-2 col-md-6 single-footer-widget\">\r\n");
      out.write("            <h4>Top Products</h4>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">Managed Website</a></li>\r\n");
      out.write("              <li><a href=\"#\">Manage Reputation</a></li>\r\n");
      out.write("              <li><a href=\"#\">Power Tools</a></li>\r\n");
      out.write("              <li><a href=\"#\">Marketing Service</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-2 col-md-6 single-footer-widget\">\r\n");
      out.write("            <h4>Quick Links</h4>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">Jobs</a></li>\r\n");
      out.write("              <li><a href=\"#\">Brand Assets</a></li>\r\n");
      out.write("              <li><a href=\"#\">Investor Relations</a></li>\r\n");
      out.write("              <li><a href=\"#\">Terms of Service</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-2 col-md-6 single-footer-widget\">\r\n");
      out.write("            <h4>Features</h4>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">Jobs</a></li>\r\n");
      out.write("              <li><a href=\"#\">Brand Assets</a></li>\r\n");
      out.write("              <li><a href=\"#\">Investor Relations</a></li>\r\n");
      out.write("              <li><a href=\"#\">Terms of Service</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-2 col-md-6 single-footer-widget\">\r\n");
      out.write("            <h4>Resources</h4>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">Guides</a></li>\r\n");
      out.write("              <li><a href=\"#\">Research</a></li>\r\n");
      out.write("              <li><a href=\"#\">Experts</a></li>\r\n");
      out.write("              <li><a href=\"#\">Agencies</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-4 col-md-6 single-footer-widget\">\r\n");
      out.write("            <h4>Newsletter</h4>\r\n");
      out.write("            <p>You can trust us. we only send promo offers,</p>\r\n");
      out.write("            <div class=\"form-wrap\" id=\"mc_embed_signup\">\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-bottom row align-items-center\">\r\n");
      out.write("          <p class=\"footer-text m-0 col-lg-8 col-md-12\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("          <div class=\"col-lg-4 col-md-12 footer-social\">\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-dribbble\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-behance\"></i></a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!--================ End footer Area  =================-->\r\n");
      out.write("\r\n");
      out.write("    <!-- Optional JavaScript -->\r\n");
      out.write("    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("    <script src=\"js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"js/popper.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/stellar.js\"></script>\r\n");
      out.write("    <script src=\"vendors/lightbox/simpleLightbox.min.js\"></script>\r\n");
      out.write("    <script src=\"vendors/nice-select/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"vendors/isotope/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"vendors/isotope/isotope-min.js\"></script>\r\n");
      out.write("    <script src=\"vendors/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("    <script src=\"js/mail-script.js\"></script>\r\n");
      out.write("    <script src=\"vendors/jquery-ui/jquery-ui.js\"></script>\r\n");
      out.write("    <script src=\"vendors/counter-up/jquery.waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"vendors/counter-up/jquery.counterup.js\"></script>\r\n");
      out.write("    <script src=\"js/theme.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
