/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2026-04-27 10:00:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class single_002dblog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1777283295789L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <!-- Required meta tags -->\r\n");
      out.write("  <meta charset=\"utf-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("  <link rel=\"icon\" href=\"img/favicon.png\" type=\"image/png\" />\r\n");
      out.write("  <title>Eiser ecommerce</title>\r\n");
      out.write("  <!-- Bootstrap CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/bootstrap.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/linericon/style.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/themify-icons.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/flaticon.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/owl-carousel/owl.carousel.min.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/lightbox/simpleLightbox.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/nice-select/css/nice-select.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/animate-css/animate.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/jquery-ui/jquery-ui.css\" />\r\n");
      out.write("  <!-- main css -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/responsive.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!--================Header Menu Area =================-->\r\n");
      out.write("  <header class=\"header_area\">\r\n");
      out.write("    <div class=\"top_menu\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-7\">\r\n");
      out.write("            <div class=\"float-left\">\r\n");
      out.write("              <p>Phone: +01 256 25 235</p>\r\n");
      out.write("              <p>email: info@eiser.com</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-5\">\r\n");
      out.write("            <div class=\"float-right\">\r\n");
      out.write("              <ul class=\"right_side\">\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"cart.jsp\">\r\n");
      out.write("                    gift card\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"tracking.jsp\">\r\n");
      out.write("                    track order\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"contact.jsp\">\r\n");
      out.write("                    Contact Us\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main_menu\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light w-100\">\r\n");
      out.write("          <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("          <a class=\"navbar-brand logo_h\" href=\"index.jsp\">\r\n");
      out.write("            <img src=\"img/logo.png\" alt=\"\" />\r\n");
      out.write("          </a>\r\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\r\n");
      out.write("            aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("          <div class=\"collapse navbar-collapse offset w-100\" id=\"navbarSupportedContent\">\r\n");
      out.write("            <div class=\"row w-100 mr-0\">\r\n");
      out.write("              <div class=\"col-lg-7 pr-0\">\r\n");
      out.write("                <ul class=\"nav navbar-nav center_nav pull-right\">\r\n");
      out.write("                  <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"index.jsp\">Home</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item submenu dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("                      aria-expanded=\"false\">Shop</a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"category.jsp\">Shop Category</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"single-product.jsp\">Product Details</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"checkout.jsp\">Product Checkout</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"cart.jsp\">Shopping Cart</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item submenu dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("                      aria-expanded=\"false\">Blog</a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"blog.jsp\">Blog</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"single-blog.jsp\">Blog Details</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item submenu dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("                      aria-expanded=\"false\">Pages</a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"tracking.jsp\">Tracking</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"elements.jsp\">Elements</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"contact.jsp\">Contact</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"col-lg-5 pr-0\">\r\n");
      out.write("                <ul class=\"nav navbar-nav navbar-right right_nav pull-right\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"#\" class=\"icons\">\r\n");
      out.write("                      <i class=\"ti-search\" aria-hidden=\"true\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"#\" class=\"icons\">\r\n");
      out.write("                      <i class=\"ti-shopping-cart\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"#\" class=\"icons\">\r\n");
      out.write("                      <i class=\"ti-user\" aria-hidden=\"true\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"#\" class=\"icons\">\r\n");
      out.write("                      <i class=\"ti-heart\" aria-hidden=\"true\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("  <!--================Header Menu Area =================-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <!--================Home Banner Area =================-->\r\n");
      out.write("    <section class=\"banner_area\">\r\n");
      out.write("      <div class=\"banner_inner d-flex align-items-center\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div\r\n");
      out.write("            class=\"banner_content d-md-flex justify-content-between align-items-center\"\r\n");
      out.write("          >\r\n");
      out.write("            <div class=\"mb-3 mb-md-0\">\r\n");
      out.write("              <h2>Blog Details</h2>\r\n");
      out.write("              <p>Very us move be blessed multiply night</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"page_link\">\r\n");
      out.write("              <a href=\"index.jsp\">Home</a>\r\n");
      out.write("              <a href=\"blog.jsp\">Blog </a>\r\n");
      out.write("              <a href=\"single-blog.jsp\">Blog Details</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--================End Home Banner Area =================-->\r\n");
      out.write("\r\n");
      out.write("    <!--================Blog Area =================-->\r\n");
      out.write("	<section class=\"blog_area single-post-area section_gap\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("							<div class=\"col-lg-8 posts-list\">\r\n");
      out.write("									<div class=\"single-post\">\r\n");
      out.write("													<div class=\"feature-img\">\r\n");
      out.write("															<img class=\"img-fluid\" src=\"img/blog/main-blog/m-blog-1.jpg\" alt=\"\">\r\n");
      out.write("													</div>\r\n");
      out.write("											<div class=\"blog_details\">\r\n");
      out.write("													<h2>Second divided from form fish beast made every of seas\r\n");
      out.write("                              all gathered us saying he our</h2>\r\n");
      out.write("                          <ul class=\"blog-info-link mt-3 mb-4\">\r\n");
      out.write("                              <li><a href=\"#\"><i class=\"ti-user\"></i> Travel, Lifestyle</a></li>\r\n");
      out.write("                              <li><a href=\"#\"><i class=\"ti-comments\"></i> 03 Comments</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("													<p class=\"excert\">\r\n");
      out.write("														MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower\r\n");
      out.write("\r\n");
      out.write("													</p>\r\n");
      out.write("													<p>\r\n");
      out.write("															MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training. who has the willpower to actually \r\n");
      out.write("                          </p>\r\n");
      out.write("                          <div class=\"quote-wrapper\">\r\n");
      out.write("                            <div class=\"quotes\">\r\n");
      out.write("                                MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training.\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          \r\n");
      out.write("                          \r\n");
      out.write("                          <p>\r\n");
      out.write("                              MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower\r\n");
      out.write("\r\n");
      out.write("                          </p>\r\n");
      out.write("                          <p>\r\n");
      out.write("                              MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training. who has the willpower to actually \r\n");
      out.write("                          </p>\r\n");
      out.write("											</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"navigation-top\">\r\n");
      out.write("                    <div class=\"d-sm-flex justify-content-between text-center\">\r\n");
      out.write("                      <p class=\"like-info\"><span class=\"align-middle\"><i class=\"ti-heart\"></i></span> Lily and 4 people like this</p>\r\n");
      out.write("                      <div class=\"col-sm-4 text-center my-2 my-sm-0\">\r\n");
      out.write("                        <p class=\"comment-count\"><span class=\"align-middle\"><i class=\"ti-comment\"></i></span> 06 Comments</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <ul class=\"social-icons\">\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"ti-facebook\"></i></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"ti-twitter-alt\"></i></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"ti-dribbble\"></i></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"ti-wordpress\"></i></a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"navigation-area\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center\">\r\n");
      out.write("                                <div class=\"thumb\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <img class=\"img-fluid\" src=\"img/blog/prev.jpg\" alt=\"\">\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"arrow\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <span class=\"ti-arrow-left text-white\"></span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"detials\">\r\n");
      out.write("                                    <p>Prev Post</p>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <h4>Space The Final Frontier</h4>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center\">\r\n");
      out.write("                                <div class=\"detials\">\r\n");
      out.write("                                    <p>Next Post</p>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <h4>Telescopes 101</h4>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"arrow\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <span class=\"ti-arrow-right text-white\"></span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"thumb\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <img class=\"img-fluid\" src=\"img/blog/next.jpg\" alt=\"\">\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("                  <div class=\"blog-author\">\r\n");
      out.write("                    <div class=\"media align-items-center\">\r\n");
      out.write("                      <img src=\"img/blog/author.png\" alt=\"\">\r\n");
      out.write("                      <div class=\"media-body\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                          <h4>Harvard milan</h4>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <p>Second divided from form fish beast made. Every of seas all gathered use saying you're, he our dominion twon Second divided from</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"comments-area\">\r\n");
      out.write("											<h4>05 Comments</h4>\r\n");
      out.write("											<div class=\"comment-list\">\r\n");
      out.write("                        <div class=\"single-comment justify-content-between d-flex\">\r\n");
      out.write("                          <div class=\"user justify-content-between d-flex\">\r\n");
      out.write("                              <div class=\"thumb\">\r\n");
      out.write("                                  <img src=\"img/blog/c1.png\" alt=\"\">\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"desc\">\r\n");
      out.write("                                  <p class=\"comment\">\r\n");
      out.write("                                    Multiply sea night grass fourth day sea lesser rule open subdue female fill which them Blessed, give fill lesser bearing multiply sea night grass fourth day sea lesser \r\n");
      out.write("                                  </p>\r\n");
      out.write("\r\n");
      out.write("                                  <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                      <h5>\r\n");
      out.write("                                        <a href=\"#\">Emilly Blunt</a>\r\n");
      out.write("                                      </h5>\r\n");
      out.write("                                      <p class=\"date\">December 4, 2017 at 3:12 pm </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"reply-btn\">\r\n");
      out.write("                                      <a href=\"#\" class=\"btn-reply text-uppercase\">reply</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  \r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"comment-list\">\r\n");
      out.write("                          <div class=\"single-comment justify-content-between d-flex\">\r\n");
      out.write("                              <div class=\"user justify-content-between d-flex\">\r\n");
      out.write("                                  <div class=\"thumb\">\r\n");
      out.write("                                      <img src=\"img/blog/c2.png\" alt=\"\">\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"desc\">\r\n");
      out.write("                                      <p class=\"comment\">\r\n");
      out.write("                                        Multiply sea night grass fourth day sea lesser rule open subdue female fill which them Blessed, give fill lesser bearing multiply sea night grass fourth day sea lesser \r\n");
      out.write("                                      </p>\r\n");
      out.write("    \r\n");
      out.write("                                      <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                                        <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                          <h5>\r\n");
      out.write("                                            <a href=\"#\">Emilly Blunt</a>\r\n");
      out.write("                                          </h5>\r\n");
      out.write("                                          <p class=\"date\">December 4, 2017 at 3:12 pm </p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("    \r\n");
      out.write("                                        <div class=\"reply-btn\">\r\n");
      out.write("                                          <a href=\"#\" class=\"btn-reply text-uppercase\">reply</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                      \r\n");
      out.write("                                  </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"comment-list\">\r\n");
      out.write("                          <div class=\"single-comment justify-content-between d-flex\">\r\n");
      out.write("                              <div class=\"user justify-content-between d-flex\">\r\n");
      out.write("                                  <div class=\"thumb\">\r\n");
      out.write("                                      <img src=\"img/blog/c3.png\" alt=\"\">\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"desc\">\r\n");
      out.write("                                      <p class=\"comment\">\r\n");
      out.write("                                        Multiply sea night grass fourth day sea lesser rule open subdue female fill which them Blessed, give fill lesser bearing multiply sea night grass fourth day sea lesser \r\n");
      out.write("                                      </p>\r\n");
      out.write("    \r\n");
      out.write("                                      <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                                        <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                          <h5>\r\n");
      out.write("                                            <a href=\"#\">Emilly Blunt</a>\r\n");
      out.write("                                          </h5>\r\n");
      out.write("                                          <p class=\"date\">December 4, 2017 at 3:12 pm </p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("    \r\n");
      out.write("                                        <div class=\"reply-btn\">\r\n");
      out.write("                                          <a href=\"#\" class=\"btn-reply text-uppercase\">reply</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                      \r\n");
      out.write("                                  </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("											</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"comment-form\">\r\n");
      out.write("											<h4>Leave a Reply</h4>\r\n");
      out.write("											<form class=\"form-contact comment_form\" action=\"#\" id=\"commentForm\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                          <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <textarea class=\"form-control w-100\" name=\"comment\" id=\"comment\" cols=\"30\" rows=\"9\" placeholder=\"Write Comment\"></textarea>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col-sm-6\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                              <input class=\"form-control\" name=\"name\" id=\"name\" type=\"text\" placeholder=\"Name\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col-sm-6\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                              <input class=\"form-control\" name=\"email\" id=\"email\" type=\"email\" placeholder=\"Email\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                              <input class=\"form-control\" name=\"website\" id=\"website\" type=\"text\" placeholder=\"Website\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <button type=\"submit\" class=\"main_btn\">Send Message</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </form>\r\n");
      out.write("									</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-lg-4\">\r\n");
      out.write("                <div class=\"blog_right_sidebar\">\r\n");
      out.write("                      <aside class=\"single_sidebar_widget search_widget\">\r\n");
      out.write("                          <form action=\"#\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                              <div class=\"input-group mb-3\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"Search Keyword\">\r\n");
      out.write("                                <div class=\"input-group-append\">\r\n");
      out.write("                                  <button class=\"btn\" type=\"button\"><i class=\"ti-search\"></i></button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button class=\"main_btn rounded-0 w-100\" type=\"submit\">Search</button>\r\n");
      out.write("                          </form>\r\n");
      out.write("                      </aside>\r\n");
      out.write("\r\n");
      out.write("                      <aside class=\"single_sidebar_widget post_category_widget\">\r\n");
      out.write("                        <h4 class=\"widget_title\">Category</h4>\r\n");
      out.write("                        <ul class=\"list cat-list\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                                    <p>Resaurant food</p>\r\n");
      out.write("                                    <p>(37)</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                                    <p>Travel news</p>\r\n");
      out.write("                                    <p>(10)</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                                    <p>Modern technology</p>\r\n");
      out.write("                                    <p>(03)</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                                    <p>Product</p>\r\n");
      out.write("                                    <p>(11)</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                                    <p>Inspiration</p>\r\n");
      out.write("                                    <p>(21)</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                                    <p>Health Care</p>\r\n");
      out.write("                                    <p>(21)</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </aside>\r\n");
      out.write("\r\n");
      out.write("                      <aside class=\"single_sidebar_widget popular_post_widget\">\r\n");
      out.write("                          <h3 class=\"widget_title\">Recent Post</h3>\r\n");
      out.write("                          <div class=\"media post_item\">\r\n");
      out.write("                              <img src=\"img/blog/popular-post/post1.jpg\" alt=\"post\">\r\n");
      out.write("                              <div class=\"media-body\">\r\n");
      out.write("                                  <a href=\"single-blog.jsp\">\r\n");
      out.write("                                      <h3>From life was you fish...</h3>\r\n");
      out.write("                                  </a>\r\n");
      out.write("                                  <p>January 12, 2019</p>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"media post_item\">\r\n");
      out.write("                              <img src=\"img/blog/popular-post/post2.jpg\" alt=\"post\">                              \r\n");
      out.write("                              <div class=\"media-body\">\r\n");
      out.write("                                  <a href=\"single-blog.jsp\">\r\n");
      out.write("                                      <h3>The Amazing Hubble</h3>\r\n");
      out.write("                                  </a>\r\n");
      out.write("                                  <p>02 Hours ago</p>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"media post_item\">\r\n");
      out.write("                              <img src=\"img/blog/popular-post/post3.jpg\" alt=\"post\">                              \r\n");
      out.write("                              <div class=\"media-body\">\r\n");
      out.write("                                  <a href=\"single-blog.jsp\">\r\n");
      out.write("                                      <h3>Astronomy Or Astrology</h3>\r\n");
      out.write("                                  </a>\r\n");
      out.write("                                  <p>03 Hours ago</p>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"media post_item\">\r\n");
      out.write("                              <img src=\"img/blog/popular-post/post4.jpg\" alt=\"post\">\r\n");
      out.write("                              <div class=\"media-body\">\r\n");
      out.write("                                  <a href=\"single-blog.jsp\">\r\n");
      out.write("                                      <h3>Asteroids telescope</h3>\r\n");
      out.write("                                  </a>\r\n");
      out.write("                                  <p>01 Hours ago</p>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </aside>\r\n");
      out.write("                      <aside class=\"single_sidebar_widget tag_cloud_widget\">\r\n");
      out.write("                          <h4 class=\"widget_title\">Tag Clouds</h4>\r\n");
      out.write("                          <ul class=\"list\">\r\n");
      out.write("                              <li>\r\n");
      out.write("                                  <a href=\"#\">project</a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li>\r\n");
      out.write("                                  <a href=\"#\">love</a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li>\r\n");
      out.write("                                  <a href=\"#\">technology</a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li>\r\n");
      out.write("                                  <a href=\"#\">travel</a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li>\r\n");
      out.write("                                  <a href=\"#\">restaurant</a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li>\r\n");
      out.write("                                  <a href=\"#\">life style</a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li>\r\n");
      out.write("                                  <a href=\"#\">design</a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li>\r\n");
      out.write("                                  <a href=\"#\">illustration</a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </aside>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                      <aside class=\"single_sidebar_widget instagram_feeds\">\r\n");
      out.write("                        <h4 class=\"widget_title\">Instagram Feeds</h4>\r\n");
      out.write("                        <ul class=\"instagram_row flex-wrap\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                  <img class=\"img-fluid\" src=\"img/instagram/widget-i1.png\" alt=\"\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                  <img class=\"img-fluid\" src=\"img/instagram/widget-i2.png\" alt=\"\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                  <img class=\"img-fluid\" src=\"img/instagram/widget-i3.png\" alt=\"\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                  <img class=\"img-fluid\" src=\"img/instagram/widget-i4.png\" alt=\"\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                  <img class=\"img-fluid\" src=\"img/instagram/widget-i5.png\" alt=\"\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                  <img class=\"img-fluid\" src=\"img/instagram/widget-i6.png\" alt=\"\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </aside>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                      <aside class=\"single_sidebar_widget newsletter_widget\">\r\n");
      out.write("                        <h4 class=\"widget_title\">Newsletter</h4>\r\n");
      out.write("\r\n");
      out.write("                        <form action=\"#\">\r\n");
      out.write("                          <div class=\"form-group\">\r\n");
      out.write("                            <input type=\"email\" class=\"form-control\" placeholder=\"Enter email\" required>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <button class=\"main_btn rounded-0 w-100\" type=\"submit\">Subscribe</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                      </aside>\r\n");
      out.write("                  </div>\r\n");
      out.write("							</div>\r\n");
      out.write("					</div>\r\n");
      out.write("			</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!--================Blog Area =================-->\r\n");
      out.write("\r\n");
      out.write("    <!--================ start footer Area  =================-->\r\n");
      out.write("    <footer class=\"footer-area section_gap\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-2 col-md-6 single-footer-widget\">\r\n");
      out.write("              <h4>Top Products</h4>\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><a href=\"#\">Managed Website</a></li>\r\n");
      out.write("                <li><a href=\"#\">Manage Reputation</a></li>\r\n");
      out.write("                <li><a href=\"#\">Power Tools</a></li>\r\n");
      out.write("                <li><a href=\"#\">Marketing Service</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-2 col-md-6 single-footer-widget\">\r\n");
      out.write("              <h4>Quick Links</h4>\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><a href=\"#\">Jobs</a></li>\r\n");
      out.write("                <li><a href=\"#\">Brand Assets</a></li>\r\n");
      out.write("                <li><a href=\"#\">Investor Relations</a></li>\r\n");
      out.write("                <li><a href=\"#\">Terms of Service</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-2 col-md-6 single-footer-widget\">\r\n");
      out.write("              <h4>Features</h4>\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><a href=\"#\">Jobs</a></li>\r\n");
      out.write("                <li><a href=\"#\">Brand Assets</a></li>\r\n");
      out.write("                <li><a href=\"#\">Investor Relations</a></li>\r\n");
      out.write("                <li><a href=\"#\">Terms of Service</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-2 col-md-6 single-footer-widget\">\r\n");
      out.write("              <h4>Resources</h4>\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><a href=\"#\">Guides</a></li>\r\n");
      out.write("                <li><a href=\"#\">Research</a></li>\r\n");
      out.write("                <li><a href=\"#\">Experts</a></li>\r\n");
      out.write("                <li><a href=\"#\">Agencies</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 single-footer-widget\">\r\n");
      out.write("              <h4>Newsletter</h4>\r\n");
      out.write("              <p>You can trust us. we only send promo offers,</p>\r\n");
      out.write("              <div class=\"form-wrap\" id=\"mc_embed_signup\">\r\n");
      out.write("                <form target=\"_blank\" action=\"https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01\"\r\n");
      out.write("                  method=\"get\" class=\"form-inline\">\r\n");
      out.write("                  <input class=\"form-control\" name=\"EMAIL\" placeholder=\"Your Email Address\" onfocus=\"this.placeholder = ''\"\r\n");
      out.write("                    onblur=\"this.placeholder = 'Your Email Address '\" required=\"\" type=\"email\">\r\n");
      out.write("                  <button class=\"click-btn btn btn-default\">Subscribe</button>\r\n");
      out.write("                  <div style=\"position: absolute; left: -5000px;\">\r\n");
      out.write("                    <input name=\"b_36c4fd991d266f23781ded980_aefe40901a\" tabindex=\"-1\" value=\"\" type=\"text\">\r\n");
      out.write("                  </div>\r\n");
      out.write("    \r\n");
      out.write("                  <div class=\"info\"></div>\r\n");
      out.write("                </form>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"footer-bottom row align-items-center\">\r\n");
      out.write("            <p class=\"footer-text m-0 col-lg-8 col-md-12\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-12 footer-social\">\r\n");
      out.write("              <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("              <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("              <a href=\"#\"><i class=\"fa fa-dribbble\"></i></a>\r\n");
      out.write("              <a href=\"#\"><i class=\"fa fa-behance\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("    <!--================ End footer Area  =================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Optional JavaScript -->\r\n");
      out.write("    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("    <script src=\"js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"js/popper.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/stellar.js\"></script>\r\n");
      out.write("    <script src=\"vendors/lightbox/simpleLightbox.min.js\"></script>\r\n");
      out.write("    <script src=\"vendors/nice-select/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"vendors/isotope/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"vendors/isotope/isotope-min.js\"></script>\r\n");
      out.write("    <script src=\"vendors/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("    <script src=\"js/mail-script.js\"></script>\r\n");
      out.write("    <script src=\"js/theme.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
